[metadata]
creation_date = "2026/08/09"
integration = []
maturity = "development"
updated_date = "2026/08/09"

[rule]
actions = []
author = ["elastic"]
description = "This is a simple KQL rule to get an alert for each host identified."
enabled = false
exceptions_list = []
false_positives = []
filters = []
from = "now-6m"
index = [
    "apm-*-transaction*",
    "auditbeat-*",
    "endgame-*",
    "filebeat-*",
    "logs-*",
    "packetbeat-*",
    "traces-apm*",
    "winlogbeat-*",
    "-*elastic-cloud-logs-*",
]
interval = "5m"
language = "kuery"
license = ""
max_signals = 100
name = "Detect hosts"
references = []
related_integrations = []
required_fields = []
risk_score = 21
risk_score_mapping = []
rule_id = "f7181381-de17-4dc3-b64e-d9ecfd43c5fa"
setup = ""
severity = "low"
severity_mapping = []
tags = []
threat = []
to = "now"
type = "query"

query = '''
host.hostname: *
'''



[rule.meta]
kibana_siem_app_url = "http://192.168.122.54:5601/app/security"

